#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
import argparse

# Import from proj
import proj
from proj.lib import clean_data

if __name__ == '__main__':
    usage = '%(prog)s'
    description = 'proj_description'
    # https://docs.python.org/3/library/argparse.html
    # https://docs.python.org/3/howto/argparse.html
    parser = argparse.ArgumentParser(description=description, usage=usage)
    args = parser.parse_args()
